# Generated by Django 4.0 on 2022-02-13 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='days',
            field=models.PositiveSmallIntegerField(default=10, null=True, verbose_name='Лимит опросов'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='period',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Кол-во опросов'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Учащийся', 'Учащийся'), ('Другое', 'Другое'), ('Работаю', 'Работаю'), ('Безработный', 'Безработный'), ('Самозанятый', 'Самозанятый'), ('Пенсионер', 'Пенсионер')], max_length=17, null=True, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='report',
            name='GotPills',
            field=models.CharField(choices=[('Не нуждаюсь', 'Не нуждаюсь'), ('Да', 'Да'), ('Нет', 'Нет')], max_length=11, null=True, verbose_name='Получили ли вы лекарственые средства'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 12, 25, 24, 26825), verbose_name='Дата и время опроса'),
        ),
    ]
