# Generated by Django 4.0 on 2022-02-13 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_days_alter_customuser_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Работаю', 'Работаю'), ('Учащийся', 'Учащийся'), ('Другое', 'Другое'), ('Самозанятый', 'Самозанятый'), ('Безработный', 'Безработный'), ('Пенсионер', 'Пенсионер')], max_length=17, null=True, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='report',
            name='GotPills',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Не нуждаюсь', 'Не нуждаюсь'), ('Да', 'Да')], max_length=11, null=True, verbose_name='Получили ли вы лекарственые средства'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cough',
            field=models.BooleanField(default=False, null=True, verbose_name='Кашель'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 13, 3, 41, 202042), verbose_name='Дата и время опроса'),
        ),
        migrations.AlterField(
            model_name='report',
            name='diarrhea',
            field=models.BooleanField(default=False, null=True, verbose_name='Диарея'),
        ),
        migrations.AlterField(
            model_name='report',
            name='dyspnea',
            field=models.BooleanField(default=False, null=True, verbose_name='Одышка'),
        ),
        migrations.AlterField(
            model_name='report',
            name='isCalled',
            field=models.BooleanField(default=False, null=True, verbose_name='Звонил ли доктор'),
        ),
        migrations.AlterField(
            model_name='report',
            name='muscle_pain',
            field=models.BooleanField(default=False, null=True, verbose_name='Боль в мышцах'),
        ),
        migrations.AlterField(
            model_name='report',
            name='nausea',
            field=models.BooleanField(default=False, null=True, verbose_name='Тошнота'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vomiting',
            field=models.BooleanField(default=False, null=True, verbose_name='Рвота'),
        ),
    ]
